# Generated by Django 4.2.1 on 2023-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
